name: Deploy Worker
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: cfdeploy
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: (cache) restore
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package.json') }}
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          packageManager: bun
          wranglerVersion: '3.x.x'
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: deploy --var COMMIT_SHA:${{ github.sha }}
